# Generated by Django 4.2.4 on 2023-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='frase',
            field=models.CharField(default=None, max_length=144, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='github',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='img_background',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='img_sobre',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='instagram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='lenProjects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='linkedin',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sobre',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tiktok',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='twitter',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
