# Generated by Django 4.2.4 on 2023-09-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_alter_perfil_frase_alter_perfil_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='portfolio',
            field=models.URLField(null=True),
        ),
    ]
