# Generated by Django 4.2.4 on 2023-08-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0002_perfil_img_background_perfil_img_sobre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userurls',
            name='user',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='UserUrls',
        ),
    ]
